apiVersion: v1
kind: ConfigMap
metadata:
  name: db-info
data:
  DB_NAME: 'uda-db'
  DB_PORT: '5432'
  DB_USERNAME: 'postgres'
  DB_HOST: 'uda-postgres'
  
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=